service: awshackbackend

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  environment:
      MET_API_KEY: ${file(./secret_keys.yml):metOfficeAPIKey}
      TFL_API_KEY: ${file(./secret_keys.yml):tflAPIKey}
package:
  artifact: build/distributions/awshackbackend.zip

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get

